name: Static checks

on:
  push

permissions:
  contents: read

jobs:
  static-checks:
    name: 'Static checks'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Scony/godot-gdscript-toolkit@master
    - run: gdformat --check .
    - run: gdlint .
  unit-tests:
    name: 'Run GUT'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run godot once
        run: |
          ls
          cd nj6-freeze
          godot --project . --headless --quit-after 20 -e 2>/dev/null
      - name: Run test
        uses: ceceppa/godot-gut-ci@main
        with:
          godot_version: 4.2
          gut_params: -gconfig=res://.gutconfig.json
